### ISSUE TITLE
gh-issues-import.py crashes while getting labels url

### ISSUE THREAD

**Issue by tector** [mkorenkov/tools#1]
maybe github url for labels has changed?
maybe i use wrong python package version?

---

abc@xyz:~/workspace$ python gh-issues-import.py
Successfully created milestone 0.2
Successfully created milestone 0.3
Traceback (most recent call last):
  File "gh-issues-import.py", line 147, in <module>
    main()
  File "gh-issues-import.py", line 135, in main
    import_labels(labels)
  File "gh-issues-import.py", line 75, in import_labels
    res = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422: Unprocessable Entity

**Comment by mkorenkov** [comment]
I feel terribly sorry for not responding that long. Closing in favor of https://github.com/IQAndreas/github-issues-import
